# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MM - Custom Items Wiki
email: marcelo@lotuz.dev
description: > # this means to ignore newlines until "baseurl:"
  All the things you need to know to make your blocks using CustomItems
baseurl: "/CustomItems" # the subpath of your site, e.g. /blog
url: "https://marcel0ll.github.io/CustomItems/" # the base hostname & protocol for your site
# url: "http://localhost:4000/" # the base hostname & protocol for your site
twitter_username: marcel0ll
github_username:  marcel0ll

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed
